### ISSUE TITLE
MatchEndEvent

### ISSUE THREAD

**Issue by fabiooxd** [FrozedClubDevelopment/FrostCommunity#1]
### Expected behavior

That the regeneration works correctly

### Observed/Actual behavior

Error + regenerating chunks for arenas in "standalone" mode stops working

### How to Recreate (if known)

It happens when a player receives a kick during a game (for example the player receives a ban while playing)

### Stack trace

https://pastebin.com/nn5ifxJ1

### Plugin list

Frost

### Frost version

Frost - v6.9-SNAPSHOT

### Agreements

- [x] I have searched for and ensured there isn't already an open issue regarding this.

**Comment by Elb1to** [comment]
This issue is being reviewed.

**Comment by Elb1to** [comment]
The issue has been found.

To reproduce it the player must be in a party, one or more of the members get kicked and when the match ends, it will send a NullPointerException.

Though, arenas are resetting properly, the issue for breaking arena regen hasn't been found.

**Comment by Elb1to** [comment]
Issue fixed by @GatitoUwU
