### ISSUE TITLE
Please 🥇 add username into mongo document

### ISSUE THREAD

**Issue by iambestzige** [FrozedClubDevelopment/FrostCommunity#10]
### Is your feature request related to a problem?

- It will be convenient to make a website.
- It will help a lot for cracked server.

- please decide to add it. 

**It's not beyond your heart, handsome man.**

### Describe the solution you'd like.

Add username into mongo document

and change ??? on leaderboard to username

I have some idea for it.
- you can add in setting.yml
  - usernamedoc: true

if usernamedoc: true it will be add new username -> mongo document

Optional:
if username in database more than 1
-> delete all that playerdata(username = current  username) and register current player for new playerdata

### Describe alternatives you've considered.

- In order for people to choose frost, there is a variety of servers to open the server.
like player want to cracked account server or premium account server

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest Frost.

**Comment by Elb1to** [comment]
This has been added on the commit **0b62c5** (1/2/2022 @ 4:03 AM)
