### ISSUE TITLE
NPC Support

### ISSUE THREAD

**Issue by iambestzige** [FrozedClubDevelopment/FrostCommunity#11]
### Is your feature request related to a problem?

- For lonely players, no friends and no player online they can play with bots.

### Describe the solution you'd like.

- Add Leaderboard NPC
- Add NPC Stats
  - LEADERBOARD_NPC:
    /setspawn leaderboardnpc (1,2,3,kit)
    - ![image](https://user-images.githubusercontent.com/25876848/147873702-e3c5e524-a661-42f8-855a-f4921c609cb2.png)
    /setspawn statisticsnpc
    - ![image](https://user-images.githubusercontent.com/25876848/147873786-b082c161-bf0f-46d7-8a26-8f86c3d3aa92.png)
    /setspawn leaderboardnpc global
    - ![image](https://user-images.githubusercontent.com/25876848/147873817-23cb4699-9967-4e26-a83a-632815e6ea8f.png)
    LEADERBOARD_NPC_ENABLE: true
    Ref: ghostly.live
    
- Add NPC Bot fight
  - EASY MODE
  - NORMAL MODE
  - HARD MODE

### Describe alternatives you've considered.

It's not necessary, but I'd like to try to suggestion it again,  In case you think it's good.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest Frost.

**Comment by Elb1to** [comment]
The NPC Leaderboard is already in development, it will be a paid addon for Frost.
The PvP Bots (NPC BotFight) won't be added
