### ISSUE TITLE
GUI [Frost 7.0]

### ISSUE THREAD

**Issue by tdvne** [FrozedClubDevelopment/FrostCommunity#13]
### Is your feature request related to a problem?

• Would be nice to have some customizable GUI's and etc.

### Describe the solution you'd like.

• Spectator GUI
• Customizable Party Events Menu

### Describe alternatives you've considered.

• Not not really.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest Frost.

**Comment by Elb1to** [comment]
Features implemented.
