### ISSUE TITLE
Better Suggestion

### ISSUE THREAD

**Issue by iambestzige** [FrozedClubDevelopment/FrostCommunity#14]
### Is your feature request related to a problem?

I think it's going to look better.

### Describe the solution you'd like.

Add be able move on OITC Event (Respawning State)

Every Event Host -> when died shoulda auto add to spectator in event for spectate that event

Specify event type -> Duo, Trio, 1v1 (Sumo, Bracket, Gulang, SkyWar)

Add option for matchHistory -> same matchSnapshot
- WinnerUsername & LoserUsername
- Potion Effect
- Logest combo
- Hit
- Hunger
- Match Duration
- Health
- Map Name
- Percent of Potion Accuracy
- Potion Count | Soup count
Maybe spectators (not really necessary)
This suggestion for website developer 💯 

Now has username -> you can /stats, /matchhistory, other with offline player username

### Describe alternatives you've considered.

for stronger frost

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest Frost.

**Comment by Elb1to** [comment]
Duplicated suggestion.
