### ISSUE TITLE
Fix Tournament alert when tournament start

### ISSUE THREAD

**Issue by iambestzige** [FrozedClubDevelopment/FrostCommunity#16]
### Expected behavior

Don't alert on tournament start,

### Observed/Actual behavior

Fix Tournament alert when tournament start

### Stack trace

Don't have

### Plugin list

![Uploading image.png…]()

### Frost version

6.9

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.

**Comment by iambestzige** [comment]
![image](https://user-images.githubusercontent.com/25876848/149899612-8a98147f-87f1-4664-82cc-2aef15d3f21f.png)

Change this to spectate when game start (random spectate)

**Comment by Elb1to** [comment]
Added and done
