### ISSUE TITLE
Please fix force toggle visible player!

### ISSUE THREAD

**Issue by iambestzige** [FrozedClubDevelopment/FrostCommunity#2]
### Expected behavior

IDK

### Observed/Actual behavior

When playing match player was hidden in fight

### How to Recreate (if known)

fix it

### Stack trace

I don't have it

### Plugin list

![Uploading image.png…]()

### Frost version

6.9

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.

**Comment by Elb1to** [comment]
This issue has been fixed by @Lucanius69
