### ISSUE TITLE
Tournament

### ISSUE THREAD

**Issue by Cryptics1999** [FrozedClubDevelopment/FrostCommunity#20]
### Expected behavior

When stopping tournament it shoud kick player out of tournament to be able to do normal stuff

### Observed/Actual behavior

When you stop tournament players arent registered as if its stopped and stays inside the tournament even if they rejoin

### How to Recreate (if known)

Start tournament
have player join 
do /tournament stop
player is then still in tournament mode

### Stack trace

Paste your stack trace or a https://pastebin.com/ link here!

### Plugin list

some plugins

### Frost version

7.0

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.

**Comment by Elb1to** [comment]
This issue is being checked.
