### ISSUE TITLE
Giving an "Armor Stand" text when leaving the holograms blank.

### ISSUE THREAD

**Issue by Mengyboi** [FrozedClubDevelopment/FrostCommunity#21]
### Expected behavior

I expected it to not show any shadow like other holograms.

### Observed/Actual behavior

I saw a text "Armor Stand".

### How to Recreate (if known)

Change 
      - "example"
      - "&7 " This will show a blank shadow
      - "example"
      - "" This will show a text as "Armor Stand"
      - "example"

### Stack trace

https://pastebin.com/493d0e94

### Plugin list

Only Frost installed.

### Frost version

v8.0

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.

### Other

None.

**Comment by Elb1to** [comment]
Just do "&7"
