### ISSUE TITLE
Events/Queue Bug

### ISSUE THREAD

**Issue by ZackariaMC** [FrozedClubDevelopment/FrostCommunity#23]
### Expected behavior

Expected the players to still be able to queue, even if there was an on-going event.

### Observed/Actual behavior

Players were not able to use the items in their inventory, for example, if they right-clicked queue, it would be un responsive. 

### How to Recreate (if known)

An event must be created (From what we've seen)

### Stack trace

https://pastebin.com/ejGUhwdJ

### Plugin list

(https://user-images.githubusercontent.com/80424435/157088943-d4e1f6d2-b9f4-477a-b38b-ecd002042fca.png)
(https://user-images.githubusercontent.com/80424435/157088945-0d69c5aa-0814-4bb3-a560-08580854793f.png)

### Frost version

v8.1

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.

**Comment by Elb1to** [comment]
Found the issue in your stacktrace, you need to increase the size of your Queues Menu and that will fix not being able to open the menu

![image](https://user-images.githubusercontent.com/50537641/157092680-c06faa0d-d26a-4806-afaa-eb0984b218e3.png)

Issue resolved.
