### ISSUE TITLE
Events > Scoreboard not working properly

### ISSUE THREAD

**Issue by Zackaria69** [FrozedClubDevelopment/FrostCommunity#24]
### Expected behavior

Scoreboard to work properly

### Observed/Actual behavior

Scoreboard shows as the regular lobby one

### How to Recreate (if known)

Start an event in certain gamemodes

### Stack trace

There is no error
https://gyazo.com/b9582a5756ec5fead53d1be529daf179 < video

### Plugin list

![Screenshot_3032](https://user-images.githubusercontent.com/80424435/157839235-0f8f1ab2-fe72-4de3-85a4-31de146442b3.png)
![Screenshot_3031](https://user-images.githubusercontent.com/80424435/157839236-42209086-e4af-4e9c-8755-a4fdf1570c2d.png)

### Frost version

![Screenshot_3033](https://user-images.githubusercontent.com/80424435/157839288-40fe3be1-78fc-4d5f-b7a5-0bec63bed36e.png)

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.

**Comment by Elb1to** [comment]
ScoreboardAPI issue, it will be possible changed to a new API in the future.
