### ISSUE TITLE
Full editable menu

### ISSUE THREAD

**Issue by izimen** [FrozedClubDevelopment/FrostCommunity#25]
### Is your feature request related to a problem?

It depends for whom. For me, to some extent, yes, because I have one theme all over the server. However, I cannot do that for practice. All "holes" in the menu can be filled with one item.
![image](https://user-images.githubusercontent.com/82685983/158029186-275100d6-95be-4f13-9fcb-7b49f18fdeb5.png)

### Describe the solution you'd like.

In each menu, I could set each individual slot with some item. 

### Describe alternatives you've considered.

no sulution

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest Frost.

### Other

![image](https://user-images.githubusercontent.com/82685983/158029276-87ee9ce1-db03-4f20-9471-f0be10325f38.png)

**Comment by Elb1to** [comment]
This was already added on Frost 8.3.

Issue closed.
