### ISSUE TITLE
Possible to translate

### ISSUE THREAD

**Issue by izimen** [FrozedClubDevelopment/FrostCommunity#26]
### Is your feature request related to a problem?

To some extent yes, because my server is 95% one language. There are single words that are not translated.

### Describe the solution you'd like.

Possible to translate: ongoing matches, kits menu, status party ("public" and "private"), PING-RANGE-FORMAT ("unrestricted") and party menu

for example
![image](https://user-images.githubusercontent.com/82685983/158059340-46b0f6bb-06f3-4fa5-9898-2e7498fd8d66.png)

### Describe alternatives you've considered.

nothing

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest Frost.

**Comment by Elb1to** [comment]
Will be added sometime in the future.
