### ISSUE TITLE
Play again feature

### ISSUE THREAD

**Issue by MsxDevil** [FrozedClubDevelopment/FrostCommunity#28]
### Is your feature request related to a problem?

its a pretty good feature after the match ends it should give a play again paper like mmc

### Describe the solution you'd like.

add it if possible :

### Describe alternatives you've considered.

nothing

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest Frost.

**Comment by Elb1to** [comment]
Feature being added for Frost 9.0

**Comment by Elb1to** [comment]
Feature added.
