### ISSUE TITLE
Bug crítico en sistema de cola/queues

### ISSUE THREAD

**Issue by AlexCanaryYT** [FrozedClubDevelopment/FrostCommunity#3]
### Expected behavior

Las queues (unranked/ranked) deberían funcionar correctamente.

### Observed/Actual behavior

Cuando 3 jugadores entran a cola al mismo tiempo (no sé exactamente como recrearlo, pero se puede observar mejor con muchos más jugadores online entrando a queue unranked o ranked), el jugador A es emparejado con el jugador B, mientras que el jugador C es emparejado también con UNO de estos DOS jugadores mencionados anteriormente, lo que causa que un jugador de los 3 mencionados está en 2 partidas diferentes al mismo tiempo. Esto causa que el jugador que está emparejado con el jugador que ya se encuentra en otra partida totalmente diferente, no lo vea, puesto que este está en otra partida, en otro mapa.

### How to Recreate (if known)

Cuando 3 jugadores entran a cola al mismo tiempo (no sé exactamente como recrearlo, pero se puede observar mejor con muchos más jugadores online entrando a queue unranked o ranked), el jugador A es emparejado con el jugador B, mientras que el jugador C es emparejado también con UNO de estos DOS jugadores mencionados anteriormente, lo que causa que un jugador de los 3 mencionados está en 2 partidas diferentes al mismo tiempo. Esto causa que el jugador que está emparejado con el jugador que ya se encuentra en otra partida totalmente diferente, no lo vea, puesto que este está en otra partida, en otro mapa.

### Stack trace

No hay errores aparentes.

### Plugin list

Frost

### Frost version

Frost - v6.9-SNAPSHOT (última)

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.

### Other

Creo que este problema es crítico, ya que esto estropea la jugabilidad por completo, inutilizando las Rankeds y Unrankeds. Este fallo se vio muy presente en la release del servidor pvpbar.net, que también usa Frost (desconozco si es la versión oficial, o la que se filtró por internet, pero aseguran que tienen el source code)

**Comment by Elb1to** [comment]
Se está investigando por qué sucede esto.

**Comment by GatitoUwU** [comment]
Debería estar fixeado, de todas formas, está bajo pruebas.

**Comment by Elb1to** [comment]
Se re-abrirá el issue si el bug persiste.
