### ISSUE TITLE
proper hcf teamfight muffins 

### ISSUE THREAD

**Issue by muffinized** [FrozedClubDevelopment/FrostCommunity#30]
### Is your feature request related to a problem?

yes, so basically hcf teamfights is kinda cringe cuz effects n stuff isnt formal ig and its rly buggy 

### Describe the solution you'd like.

er so, we could use ihcf stuff to fix effects but i imean u can just do a runnable / listener to check if their effects are gone compared to the effects 1 tick ago :D 

also u can join cobalt.club or some server to see how hcf actually works i guess

### Describe alternatives you've considered.

like just using my own plugin to fix everything and a custom kit, but i fked it and its doodoo

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest Frost.

### Other

pew pewpew pweppewpewpepwpewppewpweewpewpewppwepewpew

**Comment by Elb1to** [comment]
FrostSpigot will have iHCF events in it, and it will be a dependency for Frost once it releases.
