### ISSUE TITLE
ranked queue scoreboard muffins not working

### ISSUE THREAD

**Issue by muffinized** [FrozedClubDevelopment/FrostCommunity#31]
### Expected behavior

ranked queue scoreboard shows up and youll be able to see the elo range ping range and the other muffins etc

### Observed/Actual behavior

the scoreboard freezes on the lobby one and doens't change, indicationg there might be an errror which was caught 

### Stack trace

nop

### Plugin list

aquacore frost funny V starting anticheat, fwost crux kb controlr bungee tab leest stuffy, deluxe menoo some plugins for death animations i mdae, thats just it ig 

### Frost version

latest 8.2 if i aint wrong

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.

### Other

976tv67t697tv796tv976tv967tv79tv67tv697tv976tv679tv76tv679tv679tv796tv769tv679v67vt97tv796tv697tv697tv67

**Comment by Elb1to** [comment]
"and the other muffins etc"

What?

**Comment by Elb1to** [comment]
No further information have been provided, issue closed due to inactivity.
