### ISSUE TITLE
Bridge

### ISSUE THREAD

**Issue by Mingokol** [FrozedClubDevelopment/FrostCommunity#32]
### Expected behavior

Bridge
Normal kill sword (no combo), shoot the dead arrow a combo (bug!)
Clip: https://imgur.com/3VaRfJH

### Observed/Actual behavior

-

### How to Recreate (if known)

-

### Stack trace

-

### Plugin list

-

### Frost version

8.7

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.

### Other

-

**Comment by Elb1to** [comment]
Format not followed properly, please re-open the issue and follow the format.
