### ISSUE TITLE
Boxing Bug

### ISSUE THREAD

**Issue by iDeagan** [FrozedClubDevelopment/FrostCommunity#33]
### Expected behavior

I expected to see the points not go up before the match starts in boxing

### Observed/Actual behavior

I saw the points increasing before the Match Started, upon hitting another player even when they didn't take damage.

### How to Recreate (if known)

Click on the player multiple times before the match starts.

### Plugin list

![image](https://user-images.githubusercontent.com/63136371/169606076-1aafe770-b3cd-4e52-ab2d-ae7e2c5e0bb9.png)

### Frost version

v8.7

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.

**Comment by Elb1to** [comment]
Issue being investigated.
