### ISSUE TITLE
Party invite requests deny optionnot working

### ISSUE THREAD

**Issue by TNTTagClub** [FrozedClubDevelopment/FrostCommunity#35]
### Expected behavior

Whenever I set party invite requests to deny in the player settings menu, players are still able to send party invites to me.

I haven't really touched any of the settings.

    PARTY_REQUESTS:
      NAME: "&5Party Invite Requests"
      SLOT: 1
      ICON: NAME_TAG
      LORE:
        - "&7If enabled, players will be"
        - "&7able to send you party invites."
        - " "
      O-ENABLED: "&7Allow party leaders to invite you"
      O-DISABLED: "&7Don't allow party leaders to invite you"
      SHOW: true

Nothing shows in console either...

### Observed/Actual behavior

It claims it will not let anyone send me party invite requests, but players still do, even when both parties are not opped and they both have the default rank.

### Stack trace

Paste your stack trace or a https://pastebin.com/ link here!

### Plugin list

AquaCore 2.6.22.jar
BetterHub - 2.0.jar
CarbonSpigot-1.4.jar
CommandDisabler-2.0.jar
CraftingStore.jar
FastAsyncWorldEdit-bukkit-21.03.26-b67f782-1287-22.3.10.jar
Frost-8.8.jar
GlobalGamerules-1.0.0.jar
HackedCore.jar
HackedServer.jar
HeadDatabase-4.16.0.jar
HolographicDisplays.jar
HPWP.jar
KarhuLoader.jar
KauriVPN-1.7.1.jar
Nameless-Plugin-2.1.1.jar
NametagEdit.jar
PingVersion.jar
Pl-Hide-Pro-2.3.2.jar
PlaceholderAPI-2.11.1.jar
ProtocolLib.jar
ServerListPlus-3.4.8-Universal.jar
SimpleHelp.jar
SpawnCommand.jar
Vault.jar
ViaRewind-2.0.2.jar
ViaVersion-4.2.1.jar
VoidTeleportPlus-3.3.2.jar
WorldEdit.jar
worldguard-6.2.jar
WorldGuardExtraFlags.jar

### Frost version

8.8

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.

**Comment by Elb1to** [comment]
Issue #35 successfully fixed.
