### ISSUE TITLE
Kit DisplayName

### ISSUE THREAD

**Issue by itzslashmc** [FrozedClubDevelopment/FrostCommunity#38]
### Is your feature request related to a problem?

At the moment you can not have a kit with a spaced name, here is an example of how MMC displays the name of No Debuff kit.

https://gyazo.com/f6a8ba7031dc09c74491a12ecbc49e87

### Describe the solution you'd like.

Command /kit displayName <name>
This command will allow you to change color to specific Kits, add spaces, etc. without modifying the actual name of the Kit (f.e. Kit Name: NoDebuff, Kit DisplayName: "&e&lNEW &eNo Debuff"

### Describe alternatives you've considered.

N/A

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest Frost.

**Comment by Elb1to** [comment]
Feature added, it will be publicly available on Frost v10.0.
Customers that have bought source-code can pull the new commits.
