### ISSUE TITLE
Add spectator menu like lunar.gg

### ISSUE THREAD

**Issue by iambestzige** [FrozedClubDevelopment/FrostCommunity#4]
### Is your feature request related to a problem?

comfortable for user

### Describe the solution you'd like.

- Click on hotbar
- In Menu List all match playing
   lore:
   - ''
   - 'UserA'
   - 'vs'
   - 'UserB'
   - ''
   - 'Match Details:'
   - 'Map: XXXX'
   - 'Duration: 11.11'
   - 'Other if u want'
   - ''

### Describe alternatives you've considered.

for new customer to determine for purchase frost

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest Frost.

**Comment by iambestzige** [comment]
like lunar.gg

**Comment by GatitoUwU** [comment]
Feature implemeted
