### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by steak20** [FrozedClubDevelopment/FrostCommunity#40]
### Is your feature request related to a problem?

No.

### Describe the solution you'd like.

I want the player visibility to be saved on enabled/disabled so that you don't have to type the /tpv everytime.

So that if I toggle the Player visibility on enable, so that I can see the players, I want it to be enabled for the whole time until I disable it because it's annoying to type the command every time.

### Describe alternatives you've considered.

N/A

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest Frost.

### Other

Thanks for taking the time to read my suggestion.

**Comment by TNTTagClub** [comment]
Are you sure it's not an issue on your side? tpv saves my settings even when I relog/restart my server..

**Comment by Elb1to** [comment]
@steak20 What's your Discord # and ID?

**Comment by Elb1to** [comment]
This issue is related to your MongoDB server, player data and settings do save properly.
