### ISSUE TITLE
Title system / leaderboard placeholder

### ISSUE THREAD

**Issue by OceanTw** [FrozedClubDevelopment/FrostCommunity#42]
### Is your feature request related to a problem?

Nope

### Describe the solution you'd like.

1: Add a titles system, like MMC's, and we can add our own titles
2. A placeholder that returns to player's leaderboard position, like [#1 Nodebuff] or [#1 Global]

### Describe alternatives you've considered.

Nope

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest Frost.

**Comment by Elb1to** [comment]
I'll consider about whether or not to add the first one.
The second one already exists. https://wiki.frostpractice.com/frost-wiki/important/faq#regarding-placeholderapi
