### ISSUE TITLE
Adding support for MySql

### ISSUE THREAD

**Issue by Drock09** [FrozedClubDevelopment/FrostCommunity#43]
### Is your feature request related to a problem?

So yeh its pain to manage mongo db so if possible add support for MySql as well 🙂

### Describe the solution you'd like.

none

### Describe alternatives you've considered.

none

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest Frost.

**Comment by Elb1to** [comment]
MySQL wouldn't be able to handle all the data and operations done within Frost as it does with MongoDB, so it won't be added.

Optionally, you can use Robo3T to manage MongoDB like you would do when using PhpMyAdmin for MySQL.
Keep in mind that you'll need to allow remote connections and have security setup to prevent any intruders from accessing your DB.
