### ISSUE TITLE
FFA Bug

### ISSUE THREAD

**Issue by steak20** [FrozedClubDevelopment/FrostCommunity#44]
### Expected behavior

Speed and Fire res potions can be drinked and healing potions and enderpearls can be thrown.

### Observed/Actual behavior

Speed and Fire res potions can be drinked and healing potions and enderpearls cannot be thrown.

### How to Recreate (if known)

https://www.youtube.com/watch?v=CMdyU4ofrSo

### Stack trace
None

### Plugin list

https://prnt.sc/y8rpJn7vN7va
https://prnt.sc/pa8De_NNqaO8

### Frost version

10.6

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.

**Comment by Elb1to** [comment]
The bug has been fixed, issue closed.
