### ISSUE TITLE
Cannot break/place blocks

### ISSUE THREAD

**Issue by steak20** [FrozedClubDevelopment/FrostCommunity#45]
### Expected behavior

I want to be able to break and place blocks when I am in gamemode 1.

### Observed/Actual behavior

I am not able to break and place blocks when I am in gamemode 1.

### How to Recreate (if known)

No

### Stack trace
None

### Plugin list

https://prnt.sc/y8rpJn7vN7va
https://prnt.sc/pa8De_NNqaO8

### Frost version

10.6

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.

**Comment by Elb1to** [comment]
The bug has been fixed, issue closed.
