### ISSUE TITLE
Not able to hit players in Events

### ISSUE THREAD

**Issue by steak20** [FrozedClubDevelopment/FrostCommunity#46]
### Expected behavior

I want to be able to hit players in Events. (Sumo & TNTTag was tested and it's not possible)

### Observed/Actual behavior

I am not able to hit players in Events. (Sumo & TNTTag was tested and it's not possible)

### How to Recreate (if known)

I am not able to recreate it at the moment.

### Stack trace

No

### Plugin list

https://prnt.sc/y8rpJn7vN7va
https://prnt.sc/pa8De_NNqaO8

### Frost version

10.6

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.

**Comment by Elb1to** [comment]
The bug has been fixed, issue closed.
