### ISSUE TITLE
Player movement when in game

### ISSUE THREAD

**Issue by Aythaa** [FrozedClubDevelopment/FrostCommunity#47]
### Expected behavior

https://streamable.com/0u0req

This is a video on what happens above

### Observed/Actual behavior

https://streamable.com/0u0req

### How to Recreate (if known)

I don't have any idea how this happened.

### Stack trace

If your talking about my logs it's this.

[latest (1).log](https://github.com/FrozedClubDevelopment/FrostCommunity/files/9642489/latest.1.log)

### Plugin list

AquaCore
BlockCommandTab
Citizens
ColoredArmor
CommandNPC
Crux
FAWE
Hawk
ItemEditor
Multiverse-core
PlaceholderAPI
ProtocolLIB
ProtocolSupport
Skript
Vault
ViaRewind
ViaVersion
VoidWorld
WorldEdit

### Frost version

10.7 the latest currently

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.

**Comment by Elb1to** [comment]
Issue solved 2 weeks ago.
