### ISSUE TITLE
Player Animation 

### ISSUE THREAD

**Issue by OceanTw** [FrozedClubDevelopment/FrostCommunity#48]
### Is your feature request related to a problem?

No

### Describe the solution you'd like.

Make the player animation flys out when the player died

### Describe alternatives you've considered.

no

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest Frost.

**Comment by Elb1to** [comment]
Please elaborate and provide an example

**Comment by OceanTw** [comment]
> Please elaborate and provide an example

https://youtu.be/vTVQmmpWHsU
