### ISSUE TITLE
Translating

### ISSUE THREAD

**Issue by izimen** [FrozedClubDevelopment/FrostCommunity#49]
### Is your feature request related to a problem?

no

### Describe the solution you'd like.

translate this lines

### Describe alternatives you've considered.

translate this lines
![image](https://user-images.githubusercontent.com/82685983/194638240-2520cb70-3bb7-4cdf-bec5-385ca1ce6c27.png)

![image](https://user-images.githubusercontent.com/82685983/194638260-3fe32ad9-14f0-4593-879c-3a2b3a4e7155.png)

![image](https://user-images.githubusercontent.com/82685983/194638276-da3b6079-ab68-4e2e-8904-e55028fdf036.png)

![image](https://user-images.githubusercontent.com/82685983/194638324-c4dbaeed-739e-4703-b036-c7b1cbe55129.png)

![image](https://user-images.githubusercontent.com/82685983/194638338-89ff916c-53ea-4e22-8694-512b2a0c129c.png)

![image](https://user-images.githubusercontent.com/82685983/194638353-d658bb46-654a-4bcf-b1bc-3bee71fe2904.png)

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest Frost.

**Comment by Elb1to** [comment]
PlaceholderAPI has been added
