### ISSUE TITLE
Event Suggestion 🥇 

### ISSUE THREAD

**Issue by iambestzige** [FrozedClubDevelopment/FrostCommunity#5]
### Is your feature request related to a problem?

related to a problem

### Describe the solution you'd like.

Add event spectator:
- auto add spectator mode when died or loses (on event)

Add kit select menu:
- after click host FFA, Bracket -> action open menu kit selector for select host kit ffa, bracket

Add TNTRun Event:
- if someone don't want this, just disable on config
- if disable don't register it on plugin register

Fix Force Player Shown:
- Should fully fix!

Fix OITC Respawning:
- OITC Respawning state shoulda can move (in my opinion)
- OITC Respawing state shoulda hidden to player alive

### Describe alternatives you've considered.

Please :

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest Frost.

**Comment by Elb1to** [comment]
Please open separate issues for each bug report and suggestion 😭
