### ISSUE TITLE
Kit Editor Bug

### ISSUE THREAD

**Issue by TeruHUB** [FrozedClubDevelopment/FrostCommunity#50]
### Expected behavior

https://user-images.githubusercontent.com/80040321/206263429-efb38a99-7c8a-48e3-9bcb-291b137f9ca5.mp4

Cannot change inventory

### Observed/Actual behavior

when trying change some items disappear

### How to Recreate (if known)

go in one kit with some items, move them for few seconds and they disappear

### Stack trace

Paste your stack trace or a https://pastebin.com/ link here!

### Plugin list

https://user-images.githubusercontent.com/80040321/206263429-efb38a99-7c8a-48e3-9bcb-291b137f9ca5.mp4

### Frost version

Latest (11.5)

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.

**Comment by Elb1to** [comment]
Solved.
