### ISSUE TITLE
Bug duel in spawn

### ISSUE THREAD

**Issue by Ekelgans** [FrozedClubDevelopment/FrostCommunity#52]
### Expected behavior

That when dueling it appears on the map that corresponds to it

### Observed/Actual behavior

When he enters the game, whatever (It happened to me in Notch and Bridges), they appear in the spawn (With the armor and everything necessary for the duel), that is, it is as if they were dueling in the spawn
![image](https://user-images.githubusercontent.com/92401675/216689636-e1b6109a-58ac-4f03-bd57-c92e7b075c96.png)

### How to Recreate (if known)

It's random

### Stack trace

(https://hastebin.com/share/popavamuvi.makefile)

### Plugin list

![image](https://user-images.githubusercontent.com/92401675/216691671-6b759420-c3a3-4b47-aaec-7f34f0b2743f.png)

### Frost version

![image](https://user-images.githubusercontent.com/92401675/216692180-8c89fa87-e987-489f-91bb-b685126be8f1.png)

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.

**Comment by Elb1to** [comment]
And update has been released to address these clientside issues and hopefully fix them. Please test the new version and let me know if it's working as intended.

**Comment by Elb1to** [comment]
Issue solved.
