### ISSUE TITLE
Spawnpoints issue

### ISSUE THREAD

**Issue by SMS221** [FrozedClubDevelopment/FrostCommunity#53]
### Expected behavior

People are having problems with duels in the arena. The spawnpoint is okay and located one block above the spawnpoint. One issue is that in sumo duels, players can't see their opponent. This is causing problems with their rankings. In other arenas, players sometimes fall into the void and the match ends. Additionally, some players are spawning in the lobby instead of the arena during a match. The anticheat has been removed, but the problems are still happening.

### Observed/Actual behavior

When i select a game with the selector or the /duel, it happen sometimes that one of the players fell into the void. And sometimes they spawn at the spawn. And 5/10 times i cant see the opponent in sumo.

### Stack trace

Paste your stack trace or a https://pastebin.com/ link here!

### Plugin list

Using carbonspigot (latest)

Plugin list:
Aquacore
Carbonspigot-3.0
crux
FastAsyncWorldEdit-bukkit
PlaceholderAPI-2.10.8.
PolarApi
PolarLoader
Portal
ViaRewind-2.0.2-patched
ViaVersion-4.5.1
Worldedit

### Frost version

12.1

### Confirmations

- [X] I have searched for and ensured there isn't already an open issue regarding this.

### Other

I have tried to remove the "polar anticheat".

**Comment by RedolentHalo** [comment]
It works fine for me

**Comment by Ekelgans** [comment]
The same thing happens to me except the sumo

**Comment by Elb1to** [comment]
And update has been released to address these clientside issues and hopefully fix them. Please test the new version and let me know if it's working as intended.

**Comment by Elb1to** [comment]
Issue solved.
