### ISSUE TITLE
Bridges map not resetting 

### ISSUE THREAD

**Issue by RedolentHalo** [FrozedClubDevelopment/FrostCommunity#54]
### Expected behavior

Hello the maps of bridge doesn't get reset

### Observed/Actual behavior

So, when i play bridge there is already block placed and premade bridges when I checked the arena it looked fine

### Stack trace

Paste your stack trace or a https://pastebin.com/ link here!

### Plugin list

![image](https://user-images.githubusercontent.com/86344714/217079281-57cf8c7c-208a-465f-b0c0-68bcaeaab511.png)
![image](https://user-images.githubusercontent.com/86344714/217079302-b6ac0090-1066-4f9e-ab1c-fb5053ab93ec.png)

### Frost version

12.2

### Confirmations

- [X] I have searched for and ensured there isn't already an open issue regarding this.

**Comment by Elb1to** [comment]
The blocks might be there if you didn't shutdown your server properly or if it crashed in the past.
You can check each arena copy with /arena manage, and also update or reset the arena copy chunks with /chunk.

**Comment by RedolentHalo** [comment]
Issue fixed
