### ISSUE TITLE
Missing colour codes and config for BattleRush

### ISSUE THREAD

**Issue by xodutty** [FrozedClubDevelopment/FrostCommunity#58]
### Expected behavior

- The ability to edit the messages in messages.yml
- The correct colour codes applied to the text in the chat.

### Observed/Actual behavior

- No colourred text, replaced instead with the symbols
- Sometimes missing formatting, IGNs etc.
- It does not exist in the messages.yml file to availabley edit
![image](https://user-images.githubusercontent.com/127922330/225215863-11bc1e22-8b34-4829-a224-22353db18be7.png)
![image](https://user-images.githubusercontent.com/127922330/225215896-1e8c1414-b582-4905-9311-8d5698ad2456.png)

### How to Recreate (if known)

In the gamemode BattleRush, jump into your own team portal. Doing so will give the other player a message in chat that should read "<player> has respawned" but instead just gives an incorrectly formatted message.

### Stack trace

Paste your stack trace or a https://pastebin.com/ link here!

### Plugin list

![image](https://user-images.githubusercontent.com/127922330/225216219-7ef5e6e6-31f4-466d-8c86-03b1e3ca693b.png)

### Frost version

Version v12.3

### Confirmations

- [X] I have searched for and ensured there isn't already an open issue regarding this.

**Comment by Elb1to** [comment]
Issue solved, thanks for reporting!
Refer to commit ([4e11e0](https://github.com/FrozedClubDevelopment/Frost/commit/4e11e047615b444d51a7cf570b689167a8d0f19e))
