### ISSUE TITLE
Kit selector menu (Event Host)

### ISSUE THREAD

**Issue by iambestzige** [FrozedClubDevelopment/FrostCommunity#6]
### Is your feature request related to a problem?

For dynamics host event

### Describe the solution you'd like.

After click host FFA, Bracket -> action open menu kit selector for select kit of ffa, bracket host

### Describe alternatives you've considered.

- diversity of play

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest Frost.

**Comment by Elb1to** [comment]
Feature implemented.
