### ISSUE TITLE
Add new event host & new event feature

### ISSUE THREAD

**Issue by iambestzige** [FrozedClubDevelopment/FrostCommunity#7]
### Is your feature request related to a problem?

- Some people on my server told me why u try to add this feature

### Describe the solution you'd like.

- Add TNTRun Host
- Add Skywar Host
- Add DuoSumo Host
- Add auto spectator mode when died or loses (on event)
- Add disable & enable -> event host
  - if disable don't register that event and hidden from host menu

### Describe alternatives you've considered.

- for frost diversity

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest Frost.

**Comment by Elb1to** [comment]
Spectator mode added by @Lucanius

**Comment by Elb1to** [comment]
Everything done besides Team Setting for Events. It will be added later on.
