### ISSUE TITLE
Please fix force toggle visible player again

### ISSUE THREAD

**Issue by iambestzige** [FrozedClubDevelopment/FrostCommunity#8]
### Expected behavior

Shown enemy

### Observed/Actual behavior

I was played MLGRush, BedFight, Sumo, PearlFight, Spleef and i can't see enemy

And i got it only one on server other player don't get this

idk why

### Stack trace

Don't have

### Plugin list

![Uploading image.png…]()

### Frost version

![image](https://user-images.githubusercontent.com/25876848/147869686-3a7baab6-2ef8-416d-a2cb-6d9df4019a1e.png)

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.

**Comment by Elb1to** [comment]
This has been already fixed, the update hasn't been released yet.
